# Generated by Django 4.2.7 on 2024-01-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='length',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
